blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/DenisGithuku/Botan/issues/new?labels=enhancement&template=feature_request.md
    about: Suggest a new feature or enhancement.

  - name: Bug Report
    url: https://github.com/DenisGithuku/Botan/issues/new?labels=bug&template=bug_report.md
    about: Report a problem with the application.
