name: Build Gradle project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
#      - name: Decode Keystore
#        env:
#          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
#          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
#          RELEASE_KEYSTORE_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
#          RELEASE_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}
#
#        run: |
#          echo "${{ secrets.KEYSTORE_BASE_64 }}" | base64 --decode > keystore.jks
#
#      - name: Create missing schema directory
#        run: mkdir -p core/model/schemas
#
#      - name: Run build with Gradle Wrapper
#        env:
#          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
#          RELEASE_KEYSTORE_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
#          RELEASE_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}
#        run: ./gradlew build
      - name: Decode google-services.json (debug)
        run: |
          mkdir -p app/src
          echo "${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}" | base64 --decode > app/src/google-services.json

      - name: Run tests with Gradle Wrapper
#        env:
#          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.APP_KEYSTORE_PASSWORD }}
#          RELEASE_KEYSTORE_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
#          RELEASE_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}
        run: ./gradlew check